


      include \masm32\include\windows.inc
      include \masm32\include\gdi32.inc
      include \masm32\include\user32.inc
      include \masm32\include\masm32.inc
      include \masm32\include\kernel32.inc
      include \masm32\include\ole32.inc
    include \masm32\include\oleaut32.inc
    include \masm32\include\advapi32.inc
      includelib \masm32\lib\user32.lib
      includelib \masm32\lib\kernel32.lib
      includelib \masm32\lib\ole32.lib
   includelib \masm32\lib\oleaut32.lib
   includelib \masm32\lib\advapi32.lib